pipeline {
    agent any

    triggers {
        githubPush()
    }

    options {
        checkoutToSubdirectory('diag_tester')
        buildDiscarder(logRotator(daysToKeepStr: '7'))
    }

    tools {
        allure 'Allure'
    }

    stages {
        stage('Pull from git repo diag-tester.') {
            steps {
                checkout scm
            }
            post {
                success { 
                    githubNotify status: 'SUCCESS', context: 'Pull Code' 
                }
                failure { 
                    githubNotify status: 'FAILURE', context: 'Pull Code' 
                }
            }
        }

        stage('quickstart, install dependencies') {
            steps {
                sh '''
                    chmod +x quickstart.sh
                    ./quickstart.sh
                '''
            }
            post {
                success { 
                    githubNotify status: 'SUCCESS', context: 'Install Dependencies' 
                }
                failure { 
                    githubNotify status: 'FAILURE', context: 'Install Dependencies' 
                }
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    source .venv/bin/activate
                    pytest tests/ -sv \
                        --alluredir=reports/allure-reports \
                        --junitxml=reports/pytest-result.xml
                '''
            }
            post {
                success { 
                    githubNotify status: 'SUCCESS', context: 'Run Tests' 
                }
                failure { 
                    githubNotify status: 'FAILURE', context: 'Run Tests' 
                }
            }
        }
    }

    post {
        always {
            junit 'reports/*.xml'
            allure (
                includeProperties: false, 
                jdk: '', 
                reportBuildPolicy: 'ALWAYS', 
                results: [[path: 'reports/allure-reports']]
            )
        }
    }
}