pipeline {
    agent any

    triggers {
        githubPush()
    }

    tools {
        allure 'Allure'
    }

    stages {
        stage('Pull from git repo diag-tester.') {
            steps {
                checkout scm
            }
        }

        stage('quickstart, install dependencies') {
            steps {
                sh '''
                    chmod +x quickstart.sh
                    ./quickstart.sh
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    source .venv/bin/activate
                    pytest tests/ -sv \
                        --alluredir=reports/allure-reports \
                        --junitxml=reports/pytest-result.xml
                '''
            }
        }
    }

    post {
        always {
            junit 'reports/*.xml'
            allure (
                includeProperties: false, 
                jdk: '', 
                reportBuildPolicy: 'ALWAYS', 
                results: [[path: 'reports/allure-reports']]
            )
        }
    }
}